### ISSUE TITLE
Ensure screenshotting is stable

### ISSUE THREAD

**Issue by knutole** [mapic/engine#6]
- [ ] ensure default `super` user is created, and added to phantomjs config in `engine.config.js`
- [ ] ensure screenshots always work
- [ ] enable tests for screenshots (aka test/static/)

**Comment by mirzahusadzic** [comment]
Hi Knot,
the screenshot is not working for me. I'm getting the error:

```
engine_1       | [ 0,
engine_1       |   { __v: 0,
engine_1       |     lastUpdated: 2017-03-30T11:33:31.572Z,
engine_1       |     created: 2017-03-30T11:33:31.572Z,
engine_1       |     type: 'image',
engine_1       |     description: 'Snapshot',
engine_1       |     name: 'snap-pkovotedfx.png',
engine_1       |     createdByName: 'Mapic Localhost',
engine_1       |     createdBy: 'user-690f14e6-9b8f-4d14-adb6-797770a49391',
engine_1       |     uuid: 'file-02c6b6a1-bdf5-4b7a-a945-914bfb60aa6a',
engine_1       |     _id: 58dced0b689a4a160f0022b9,
engine_1       |     access: { clients: [], projects: [], users: [Object] },
engine_1       |     data: { image: [Object] },
engine_1       |     styleTemplates: [],
engine_1       |     format: [ 'png' ],
engine_1       |     keywords: [],
engine_1       |     files: [ 'snap-pkovotedfx.png' ] } ]
engine_1       | Error: ENOENT: no such file or directory, stat '/data/images/snap-pkovotedfx.png'
engine_1       |     at Error (native)
```

But further debbuging showed that if I run phantomjs manually (with addition of --ignore-ssl-errors=true) from the command line, i.e.

```
./phantomjs --ssl-protocol=tlsv1 --ignore-ssl-errors=true --debug=true ../../../tools/phantomJS-snapshot.js '{"url":"https://localhost/","outPath":"test.png","view":{"project_id":"project-85df9567-d203-4904-b8e2-3de33706aca8","position":{"lat":59.43320477511503,"lng":8.386688232421877,"zoom":9},"layers":[],"access_token":"pk.vVXP77zb7sTOhY231DrmMiHndy2q7SbHcjXCLImr"}}'
```
I can save screenshot locally.
But if I take screenshot from the Mapic, with same parameters (I enabled debugging) I received:

```
engine_1       | stderr: 2017-03-30T11:33:01 [DEBUG] Network - Resource request error: QNetworkReply::NetworkError(ConnectionRefusedError) ( "Connection refused" ) URL: "https://localhost/"
```
Do you know what may cause the problem? Here is a complete [log.](https://github.com/mapic/engine/files/882113/screenshot_log.txt)

**Comment by knutole** [comment]
@mirzahusadzic Yeah, this is an issue with `localhost` only. We haven't had this problem with refused connection on production, because the SSL and routing are different. 

The `localhost` within `mapic/engine` is not the same `localhost` as `mapic/nginx` or your host shell operates with, for example, which is why you can only run the debug command from your host shell. 

I think a fix for this issue requires a separate phantomjs command for `localhost` domain envs, perhaps with `https://localhost:3001` instead (which will hit engine server directly). Haven't looked at this, so not sure. See [nginx config](https://github.com/mapic/config-localhost/blob/master/localhost/localhost.nginx.conf) for example.
